const userConstants = {
  REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  LOGOUT: "USER_LOGOUT",

  GETME_REQUEST: "USER_GETME_REQUEST",
  GETME_SUCCESS: "USERS_GETME_SUCCESS",
  GETME_FAILURE: "USERS_GETME_FAILURE",
};
export default userConstants;
